name: gm_generate
description: A useful command-line application to provide generate class model.
version: 1.0.0
homepage: https://github.com/irwan75/gm_generate

environment:
  sdk: '>=2.14.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
